# Generated by Django 4.0.4 on 2022-07-15 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0002_chatmessage_body_alter_friend_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='msg_reciever',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='chatapp.friend'),
        ),
    ]
