# Generated by Django 4.0.4 on 2022-07-15 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0003_alter_chatmessage_msg_reciever'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='msg_reciever',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='msg_sender',
            field=models.CharField(max_length=12),
        ),
    ]
